### ISSUE TITLE
about other style image training

### ISSUE THREAD

**Issue by dandanli814** [TAMU-VITA/ShapeMatchingGAN#10]
Hi, I use another style image as following which you has shown in other place.
![snow_v2](https://user-images.githubusercontent.com/24379250/69699791-c4b5d580-1123-11ea-996e-e824165e22e5.png)
I train on this snow style image with the same parameters as you say in README.md. And then I test the model, the result is as following: (two images are with different values of l)
![2019-11-27_14_35_10 709080snow_5](https://user-images.githubusercontent.com/24379250/69699921-237b4f00-1124-11ea-8ad5-363c5a986a5e.png)
![2019-11-27_14_35_10 709080snow_0](https://user-images.githubusercontent.com/24379250/69699931-28400300-1124-11ea-912d-51b1fe659e23.png)
I don't know where the problem is.  I hope you can give some suggestions or share the parameter settings of the snow style image you trained before.
Thank you very much.

**Comment by dandanli814** [comment]
The following is your result shown in ZHIHU:

![QQ图片20191127145348](https://user-images.githubusercontent.com/24379250/69700591-c41e3e80-1125-11ea-8e2e-e1434cf64835.png)

But I can't get results like yours.

**Comment by williamyang1991** [comment]
Your stlye image (1400*960) is too huge compared to your text image (320*320) ........
Here is what I used (400*400)
![ice](https://user-images.githubusercontent.com/18130694/69701489-047ebc00-1128-11ea-9178-d8afc6e99547.png)

And I remember I didn't use --Tanglejitter, --style_loss nor --Sanglejitter in this case.

**Comment by dandanli814** [comment]
OK，thank you~ I will try this.^_^
