### ISSUE TITLE
Image Matting

### ISSUE THREAD

**Issue by noobiecoder1942** [TAMU-VITA/ShapeMatchingGAN#16]
Which algorithm have you used for image matting? Or did you use Photoshop?

**Comment by williamyang1991** [comment]
I just used Photoshop. It is easy to use and the user can control where to be used as foreground.

**Comment by noobiecoder1942** [comment]
Thank you for such a quick response. I am trying to train the model on a different dataset but I have no background in photoshop. Can you please suggest steps you followed to convert the text data used in TET-GAN paper to data used in this paper? Any steps or reference link would be really helpful!

**Comment by williamyang1991** [comment]
For a new style image, you may refer to the magic wand tool in photoshop (https://www.photoshopessentials.com/basics/selections/magic-wand-tool/)
to select its foreground. Then you fill the foreground with white and the remain region with black.
Next, use utils.text_image_preprocessing to transform black and white mask into distance-based mask (the blue and red one).
FInally, concatenate distance-based mask with your style image as the format of images in ../data/style/ and copy the result to ../data/style/.
Hope this help.

**Comment by Drod917** [comment]
@williamyang1991 Thank you for this awesome project! I've followed these instructions and have obtained an image in the same format as the those in ../data/style/ (distance map on the left, original style reference on the right) and the network nearly makes it through the first epoch before throwing 

"RuntimeError: The size of tensor a (256) must match the size of tensor b (255) at non-singleton dimension 1" 

I'm almost certain it has to do with the way I may be formatting the image, but I'm unsure. Any ideas?

**Comment by williamyang1991** [comment]
Maybe your image contains the alpha channel, i.e., RGBA channels, while our code works on RGB channels. So there is a mismatch in the channel dimension (4 v.s. 3). 
Or you can provide me with a link of your image and I will check it.

**Comment by Drod917** [comment]
Changing the length & width of my image to multiples of 8 fixed the problem. Thank you!

**Comment by noobiecoder1942** [comment]
That was really helpful! Thanks for the Photoshop instructions!
