### ISSUE TITLE
float error

### ISSUE THREAD

**Issue by BolinLi-s** [TAMU-VITA/ShapeMatchingGAN#2]
when I run : 
        sh ../script/launch_SketchModule.sh

Traceback (most recent call last):
  File "/home/lbl/work/ShapeMatchingGAN/src/trainSketchModule.py", line 46, in <module>
    main()
  File "/home/lbl/work/ShapeMatchingGAN/src/trainSketchModule.py", line 28, in main
    opts.text_datasize, trainnum=opts.Btraining_num)
  File "/home/lbl/work/ShapeMatchingGAN/src/utils.py", line 82, in load_train_batchfnames
    fnames = [('%04d.png' % (i%usenum)) for i in range(trainnum)]
TypeError: 'float' object cannot be interpreted as an integer

**Comment by BolinLi-s** [comment]
and same problems in trainSketchModule.py

**Comment by williamyang1991** [comment]
The float bugs have been fixed.
It seems that your default data type is float?
In my case, the result of integer / integer is sill an integer. 
e.g. (self.kernel_size - 1)/2  and  trainnum/batchsize*batchsize 
So there is no type error reported in the orginal code on my computer.

**Comment by BolinLi-s** [comment]
看来是我的问题。 不过都是python3 ，为什么我的整数相除会变成浮点？

**Comment by williamyang1991** [comment]
It seems that I find the reason.
My code is implenmented under python2, where integer / integer yields integer.
And in python3, integer / integer produces float.

**Comment by BolinLi-s** [comment]
so haven't you thought about making a python3 version?
