### ISSUE TITLE
about "water" image

### ISSUE THREAD

**Issue by dandanli814** [TAMU-VITA/ShapeMatchingGAN#5]
Hi, thank you for your work. Can you share the "water.png" for the dir "./data/style". I just find "fire.png", "leaf.png", "maple.png","sakura.png" and "smoke.png" in that dir. 
Thank you very much.

**Comment by williamyang1991** [comment]
I have added a link to the ''water'' image and uploaded the correspodning mask we used in the paper.
Please find them in ''./data/style/mask/''

**Comment by dandanli814** [comment]
> I have added a link to the ''water'' image and uploaded the corresponding mask we used in the paper.
> Please find them in ''./data/style/mask/''

Thank you~^_^
