### ISSUE TITLE
question about  different styles produce different deformation degrees

### ISSUE THREAD

**Issue by dandanli814** [TAMU-VITA/ShapeMatchingGAN#8]
Hi, I test my images on the pre-trained models you provied.  But I found a bit strange in the test results. 
For example, in the case of the most deformation, ie scale=1, the test results of fire and water are as follows.
![image](https://user-images.githubusercontent.com/24379250/69127312-04a60880-0ae5-11ea-936c-d20165dd512e.png)
![image](https://user-images.githubusercontent.com/24379250/69127328-0b348000-0ae5-11ea-9e17-9ccfa35641cd.png)
Why is the effect of fire deformation so obvious but water has almost no deformation feeling？

**Comment by williamyang1991** [comment]
I think there are two reasons.
First, different stlyes have different deformations. You cannot expect every style to have an obvious deformation effects as the fire. 
Second, your text is relatively large compared to the text used and trained in my paper. If the text is larrge, the scale of the deformation will consiquently look relatively small.
Maybe you can train with your own data, with large style image size, large text image size and large blur kernel, to obtain obvious water-like deformations.

**Comment by dandanli814** [comment]
Hi, my image is 320*320, just like yours, I just concat the results of the two words together. So as you say, if I want to  obtain obvious water-like deformations, I can train with large blur kernel. The method you said ”large blur kernel” is to increase the kernel_size or increase the range 8-24?

**Comment by dandanli814** [comment]
Hi, my image is 320*320, just like yours, I just concat the results of the two words together. So as you say, if I want to obtain obvious water-like deformations, I can train with large blur kernel. The method you said ”large blur kernel” is to increase the kernel_size or increase the range 8-24?

**Comment by williamyang1991** [comment]
![69127328-0b348000-0ae5-11ea-9e17-9ccfa35641cd](https://user-images.githubusercontent.com/18130694/69129888-62891f00-0aea-11ea-8f6b-3e8eae556d7a.png)

image size != text size (font size)
Large blur kerne means large standard deviation. So increasing the range 8-24 to 8-like 32 or 40.

**Comment by dandanli814** [comment]
OK, Thank you~ So what is your font size and image size?

**Comment by williamyang1991** [comment]
320*320 images, with text of 188.4pt size in Photoshop
Please take the attached .psd for reference.
[text example.zip](https://github.com/TAMU-VITA/ShapeMatchingGAN/files/3862885/text.example.zip)
