### ISSUE TITLE
question about label smoothing

### ISSUE THREAD

**Issue by dandanli814** [TAMU-VITA/ShapeMatchingGAN#9]
Hi, when I read your code :

https://github.com/TAMU-VITA/ShapeMatchingGAN/blob/90f139fede9beb16a07d00ed8f279a7c4fff2ac9/src/models.py#L164

What is the reason for doing this step (label smoothing)?

**Comment by williamyang1991** [comment]
I just intuitively want that at any time, both the paths of controllable resblock will be updated. 
I did not specifically carry out  the ablation study. So I'm not sure whether label smoothing will bring performance gains or drops. 
I guess the effect of this step is insignificant.

**Comment by dandanli814** [comment]
OK, thank you~In addition, your method is one model for one style.  If I want to implement a general model for image2text style transfer, is there any method or paper recommended?^_^

**Comment by williamyang1991** [comment]
If you want an Arbitrary-Style-Per-Model Neural Method, 
you can refer to https://github.com/ycjing/Neural-Style-Transfer-Papers for the style transfer review.

**Comment by dandanli814** [comment]
OK, thank you~^_^
